/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auto;

import java.awt.*;
import java.awt.event.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;

import javax.swing.*;
import javax.swing.event.*;
/**
 *
 * @author master
 */
public class Autobox extends javax.swing.JFrame {

    /**
     * Creates new form AutoboxB
     */
    public Autobox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        stylebtm = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        style = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dsz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dimtype = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        wsz = new javax.swing.JTextField();
        lsz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cflute = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtFilePathName = new javax.swing.JTextField();
        lblBlkSz = new javax.swing.JLabel();
        r2r2upint = new javax.swing.JLabel();
        createDxf = new javax.swing.JButton();
        btnBlkSz = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        topVal = new javax.swing.JTextField();
        jLabelTop = new javax.swing.JLabel();
        btmVal = new javax.swing.JTextField();
        jLabelBtm = new javax.swing.JLabel();
        txtFlange = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("02xx / 07xx Series Designs");

        stylebtm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0701 Auto Full OL", "0701 Auto Full OL RC", "0700 Auto Std", "0200 (Raw Edge)", "0201 (OFOTB)", "0202 (OFO)", "0203 (OFFO)", "0204 (AFM)", "0205 (IFM)", "0206 (IFM / OFFO)", "0209 (Short Top Flap)", "0209 (Gap Flaps)", "0216 (Envelope Base)" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Style:");

        style.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0215+ P&S / Rippa", "Full Overlap P&S / Rippa", "Hammer Head OL", "0200 (Raw Edge)", "0201 (OFOTB)", "0202 (OFO)", "0203 (OFFO)", "0204 (AFM)", "0205 (IFM)", "0206 (IFM / OFFO)", "0209 (Short Top Flap)" }));
        style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Pack Size:");

        jLabel5.setText("x");

        dsz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dszFocusLost(evt);
            }
        });

        jLabel6.setText("x");

        dimtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID: Internal Dimensions", "BB: Bend to Bend", "OD: Outside Dimensions" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Dim Type:");

        lsz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lszActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Flute:");

        cflute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "B", "C", "EB", "N", "F", "R", "BC" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("File Name:");

        txtFilePathName.setText("aaNewDrawing.dxf");

        lblBlkSz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBlkSz.setText("1up Blank Size:");

        r2r2upint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r2r2upint.setText("Interlock:");

        createDxf.setText("Create DXF Drawing");
        createDxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDxfActionPerformed(evt);
            }
        });

        btnBlkSz.setText("Calc Blank Size");
        btnBlkSz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlkSzActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Length Panel 1st");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton2.setText("Width Panel 1st");

        topVal.setText("0");
        topVal.setVisible(false);

        jLabelTop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTop.setText("Top OL:");
        jLabelTop.setVisible(false);

        btmVal.setText("0");
        btmVal.setVisible(false);

        jLabelBtm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBtm.setText("Btm OL:");
        jLabelBtm.setVisible(false);

        txtFlange.setText("30");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Flange:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r2r2upint, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(style, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(stylebtm, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lsz, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(wsz, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(82, 82, 82)
                                                .addComponent(jLabelTop)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(topVal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelBtm)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btmVal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)))
                                        .addGap(18, 18, 18)
                                        .addComponent(dimtype, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cflute, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFilePathName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFlange, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblBlkSz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(110, 110, 110)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(createDxf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBlkSz, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btmVal, topVal});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(style, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stylebtm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBtm)
                        .addComponent(btmVal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTop)
                        .addComponent(topVal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dimtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(wsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFlange, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFilePathName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(cflute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8)))
                .addGap(42, 42, 42)
                .addComponent(lblBlkSz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2r2upint, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBlkSz, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createDxf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dszFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dszFocusLost
        try {

            
        } catch(Exception e) {
            System.err.println("ERROR: " + e.getMessage());
            e.printStackTrace();
        } finally {

        } // end of try
    }//GEN-LAST:event_dszFocusLost

    private void lszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lszActionPerformed

    private void createDxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDxfActionPerformed
        double l = Double.parseDouble(lsz.getText());
        double w = Double.parseDouble(wsz.getText());
        double d = Double.parseDouble(dsz.getText());

        double sz[] = getIDsizes(l, w, d);
        l = sz[0];
        w = sz[1];
        d = sz[2];

        DrawDCcase oDxf = new DrawDCcase();
        oDxf.xabs = 0;
        oDxf.yabs = 0;
        oDxf.length = l;
        oDxf.width = w;
        oDxf.depth = d;
        oDxf.flute = (String) cflute.getSelectedItem();
        oDxf.flange =  Double.parseDouble(txtFlange.getText());
        oDxf.topStyle = (String) style.getSelectedItem();
        oDxf.btmStyle = (String) stylebtm.getSelectedItem();
 
        String outputDxfData = oDxf.drawCase();

        String outputDir = ""; // "../temp/";
        File f = new File(outputDir + txtFilePathName.getText());
        if(f.exists() && !f.isDirectory()) { 
          f.delete();
        }
        String outputDxfFile = outputDir + txtFilePathName.getText(); // "testfilel.dxf"; // "/var/www/temp/testfilel.dxf";

        BufferedWriter writer = null; // Note outside try block
        try {
          //create a file
          File newDxfFile = new File(outputDxfFile);

          writer = new BufferedWriter(new FileWriter(newDxfFile));
          writer.write(outputDxfData);
          writer.flush();
        } catch (Exception e) {
          e.printStackTrace();
        } finally {
          try {
            // Close the writer regardless of what happens...
            writer.close();
          } catch (Exception e) {
          }
        }
        JOptionPane.showMessageDialog(null, "Saved: " + outputDxfFile);

    }//GEN-LAST:event_createDxfActionPerformed

    
    private void btnBlkSzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlkSzActionPerformed
        double l = Double.parseDouble(lsz.getText());
        double w = Double.parseDouble(wsz.getText());
        double d = Double.parseDouble(dsz.getText());

        lblBlkSz.setText(cflute.getSelectedItem().toString());

        double sz[] = getIDsizes(l, w, d);
        l = sz[0];
        w = sz[1];
        d = sz[2];

        DrawDCcase oDxf = new DrawDCcase();
        oDxf.length = l;
        oDxf.width = w;
        oDxf.depth = d;
        oDxf.flute = (String) cflute.getSelectedItem();

        oDxf.topStyle = (String) style.getSelectedItem();
        oDxf.btmStyle = (String) stylebtm.getSelectedItem();

        oDxf.calcBlkSz();
        lblBlkSz.setText("Blank Size: " + Double.toString(oDxf.s1way) + " x " +  Double.toString(oDxf.n2way));

        parcelSizes oBjt = new parcelSizes();
        oBjt.odLength = l+4; //this.odLength;
        oBjt.odWidth = w+4; //this.odWidth;
        oBjt.odDepth = d+6; //this.odDepth;
        oBjt.style = (String) this.style.getSelectedItem() + "/" + this.stylebtm.getSelectedItem();
        oBjt.checkSizes();

    }//GEN-LAST:event_btnBlkSzActionPerformed

    private void styleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_styleActionPerformed

    
      public double[] getIDsizes(double l, double w, double d) { 
    // 0203+/0701+
    if (dimtype.getSelectedItem() == "ID: Internal Dimensions") {
      // Do nothing
    } else if (dimtype.getSelectedItem() == "OD: Outside Dimensions") {
      if (cflute.getSelectedItem().toString() == "B") {
        l = l - 6;
        w = w - 6;
        d = d - 12;
      } else if(cflute.getSelectedItem().toString() == "C") {
        l = l - 10;
        w = w - 10;
        d = d - 15; 
      } else { // E flute
        l = l - 4;
        w = w - 4;
        d = d - 8;
      } // end of if  
    } else {   // B to B
      if (cflute.getSelectedItem().toString() == "B") {
        l = l - 3;
        w = w - 3;
        d = d - 6;
      } else if(cflute.getSelectedItem().toString() == "C") {
        l = l - 5;
        w = w - 5;
        d = d - 10; 
      } else { // E flute
        l = l - 2;
        w = w - 2;
        d = d - 4;
      } // end of if        
    }
    
    double sz[] = {0,0,0};
    sz[0] = l;
    sz[1] = w;
    sz[2] = d;
    return sz;
  }  // getIDsizes
  
  public void style_ItemStateChanged(ItemEvent evt) {
//"Hammer Head OL", "0215+ P&S / Rippa", "0202 (OFO)", "0209 (Short Top Flap)", "0209 (Gap Flaps)"
   if(style.getSelectedItem()== "Hammer Head OL") {
      this.jLabelTop.setText("Hammer OL:");
      this.jLabelTop.setVisible(true); 
      this.topVal.setText("25");
      this.topVal.setVisible(true);    
   } else if(style.getSelectedItem()== "0202 (OFO)") {
    this.jLabelTop.setText("Top OL:");
    this.jLabelTop.setVisible(true); 
    this.topVal.setText("25");
    this.topVal.setVisible(true);    
   } else if(style.getSelectedItem()== "0215+ P&S / Rippa") {
    this.jLabelTop.setText("0215+ P&S:");
    this.jLabelTop.setVisible(true); 
    this.topVal.setText("65");
    this.topVal.setVisible(true);    
   } else if(style.getSelectedItem()== "0209 (Short Top Flap)") {
    this.jLabelTop.setText("Short Flap Sz:");
    this.jLabelTop.setVisible(true); 
    this.topVal.setText("30");
    this.topVal.setVisible(true);    
   } else if(style.getSelectedItem()== "0209 (Gap Flaps)") {
    this.jLabelTop.setText("Top Flap Gap:");
    this.jLabelTop.setVisible(true); 
    this.topVal.setText("6");
    this.topVal.setVisible(true);    
   } else {
    this.jLabelTop.setText(" ");
    this.jLabelTop.setVisible(false); 
    this.topVal.setText("0");
    this.topVal.setVisible(false);       
   }

  } // end of style_ItemStateChanged

  public void style_ActionPerformed(ActionEvent evt) {
    String topOL = (String) style.getSelectedItem();
    if(topOL.equals("Hammer Head OL") || topOL.equals("0202 (OFO)")) {
        topVal.setVisible(true);
        
    }
    
    

  } // end of style_ActionPerformed

  public void stylebtm_ItemStateChanged(ItemEvent evt) {
// "0700 Auto Std",  "0202 (OFO)", "0209 (Short Btm Flap)", "0209 (Gap Flaps)", "0216 (Envelope Base)"
   if(stylebtm.getSelectedItem()== "0700 Auto Std") {
      this.jLabelBtm.setText("Btm Lock OL:");
      this.jLabelBtm.setVisible(true); 
      this.btmVal.setText("25");
      this.btmVal.setVisible(true);    
   } else if(stylebtm.getSelectedItem()== "0202 (OFO)") {
    this.jLabelBtm.setText("Btm OL:");
    this.jLabelBtm.setVisible(true); 
    this.btmVal.setText("25");
    this.btmVal.setVisible(true);    
   } else if(stylebtm.getSelectedItem()== "0209 (Short Btm Flap)") {
    this.jLabelBtm.setText("Short Flap Sz:");
    this.jLabelBtm.setVisible(true); 
    this.btmVal.setText("30");
    this.btmVal.setVisible(true);    
   } else if(stylebtm.getSelectedItem()== "0209 (Gap Flaps)") {
    this.jLabelBtm.setText("Btm Flap Gap:");
    this.jLabelBtm.setVisible(true); 
    this.btmVal.setText("6");
    this.btmVal.setVisible(true);    
   } else if(stylebtm.getSelectedItem()== "0216 (Envelope Base)") {
    this.jLabelBtm.setText("Btm Lock OL:");
    this.jLabelBtm.setVisible(true); 
    this.btmVal.setText("25");
    this.btmVal.setVisible(true);    
   } else {
    this.jLabelBtm.setText(" ");
    this.jLabelBtm.setVisible(false); 
    this.btmVal.setText("0");
    this.btmVal.setVisible(false);       
   }
   
  } // end of stylebtm_ItemStateChanged

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btmVal;
    private javax.swing.JButton btnBlkSz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cflute;
    private javax.swing.JButton createDxf;
    private javax.swing.JComboBox<String> dimtype;
    private javax.swing.JTextField dsz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBtm;
    private javax.swing.JLabel jLabelTop;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lblBlkSz;
    private javax.swing.JTextField lsz;
    private javax.swing.JLabel r2r2upint;
    private javax.swing.JComboBox<String> style;
    private javax.swing.JComboBox<String> stylebtm;
    private javax.swing.JTextField topVal;
    private javax.swing.JTextField txtFilePathName;
    private javax.swing.JTextField txtFlange;
    private javax.swing.JTextField wsz;
    // End of variables declaration//GEN-END:variables
}
